spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  mail:
    host: smtp.gmail.com
    port: 587
    username: sw.lookeng@gmail.com
    password: fuvmpmvoeszazrpd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

lookeng:
  admin:
    secret-code: "LOOKENG_SECRET_777"

---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

server:
  servlet:
    session:
      cookie:
        same-site: none
        secure: false

logging:
  level:
    org.hibernate.SQL: debug

---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false